### ISSUE TITLE
Внедрение паттерна стратегия в проект.

### ISSUE THREAD

**Issue by ScorpKir** [ScorpKir/heaven-cash#58]
### Постановка проблемы

В рамках лабораторной работы нужно использовать паттерны проектирования. В связи с этим принято реализовать опредлелитель операции через паттерн **стратегия**.

### Что необходимо сделать

Существует четыре операции:

- **withdraw (снятие)** - класс определен в файле `app/internal/models/operation/operation_types/withdraw.py`
- **deposit (пополнение)** - класс определен в файле `app/internal/models/operation/operation_types/deposit.py`
- **mobile (мобильная связь)** - класс определен в файле `app/internal/models/operation/operation_types/mobile.py`
- **communal (коммуналка)** - класс определен в файле `app/internal/models/operation/operation_types/mobile.py`

**Необходимо**

 В файле `app/internal/models/operation/qualifier.py` (его надо создать) определить класс `OperationTypeQualifier`, который будет:

1. Принимать все поля класса `Operation`
2. Определять объект, который соответствует типу операции из входных данных
3. Инициализировать этот объект

- Реализовать геттер, через который можно будет получить объект нужной операции, 
- Также реализовать метод execute, через который можно будет выполнить операцию.

### Важно

- Для типов операции **communal** обязательно заполнение поля **additional**. В него должен ложиться номер квитанции.
- Для типа операции **mobile** обязательно заполнение поля **additional**. В него должен ложиться пополняемый номер телефона.

---

**Выполнить до**: 14.12

**Не заливать в ветку develop самостоятельно. Дождаться моего обзора**

**Comment by liveGine** [comment]
Реализовал класс

**Comment by ScorpKir** [comment]
Задание выполнено
